#!/bin/bash

if [ "$#" -lt 2 ]; then
    echo "Uso: $0 <ARCHIVO_TESTING> <NOMBRE_DE_LA_CARPETA_NUEVA> <NOMBRE_DEL_EJECUTABLE>"
    exit 1
fi


FILE_TO_TEST=$1
DIRNAME=$2 
OUTPUT=$3


./scripts/simplify.sh ./src ./include/ pampas $DIRNAME

cp $FILE_TO_TEST $DIRNAME

# crear makefile
echo -e "all:\n\tg++ $(basename "$FILE_TO_TEST") pampas.cpp -o $OUTPUT -lwiringPi \n\tsudo ./$OUTPUT" > $DIRNAME/makefile

echo "Archivo $FILE_TOTEST copiado en la carpeta $DIRNAME"
